# Generated by Django 3.2 on 2021-04-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('send', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('datec', models.DateField()),
            ],
        ),
    ]
