# Generated by Django 3.2 on 2021-04-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='datec',
            new_name='date',
        ),
    ]
