# Generated by Django 3.2 on 2021-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdatabase', '0002_rename_datec_doc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('send', models.TextField()),
                ('receiver', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocdatabaseDoc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('send', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'docdatabase_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.TextField(blank=True, null=True)),
                ('s_roll', models.TextField(blank=True, null=True)),
                ('img_sign', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'signature',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='doc',
        ),
    ]
