# Generated by Django 3.2 on 2021-04-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdatabase', '0003_auto_20210422_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocdatabaseDoc',
        ),
    ]
