# Generated by Django 3.2 on 2021-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdatabase', '0004_delete_docdatabasedoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocdatabaseDoc',
            fields=[
                ('id_doc', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('send', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'docdatabase_doc',
                'managed': False,
            },
        ),
    ]
