# Generated by Django 3.2 on 2021-04-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdatabase', '0005_docdatabasedoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocdatabaseDoc',
        ),
        migrations.AlterModelTable(
            name='db',
            table='Db',
        ),
        migrations.AlterModelTable(
            name='signature',
            table='Signature',
        ),
    ]
